#!/bin/bash

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && \
docker run --rm --privileged -v ~/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/nextcloud_backup:/data homeassistant/amd64-builder --all -t /data

