/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertManager: typeof import('./src/components/AlertManager.vue')['default']
    BackupConfigAddon: typeof import('./src/components/settings/BackupConfig/BackupConfigAddon.vue')['default']
    BackupConfigAutoBackup: typeof import('./src/components/settings/BackupConfig/BackupConfigAutoBackup.vue')['default']
    BackupConfigAutoClean: typeof import('./src/components/settings/BackupConfig/BackupConfigAutoClean.vue')['default']
    BackupConfigAutoStop: typeof import('./src/components/settings/BackupConfig/BackupConfigAutoStop.vue')['default']
    BackupConfigFolder: typeof import('./src/components/settings/BackupConfig/BackupConfigFolder.vue')['default']
    BackupConfigForm: typeof import('./src/components/settings/BackupConfigForm.vue')['default']
    BackupConfigMenu: typeof import('./src/components/settings/BackupConfigMenu.vue')['default']
    BackupConfigSecurity: typeof import('./src/components/settings/BackupConfig/BackupConfigSecurity.vue')['default']
    CloudDeleteDialog: typeof import('./src/components/cloud/CloudDeleteDialog.vue')['default']
    CloudList: typeof import('./src/components/cloud/CloudList.vue')['default']
    CloudListItem: typeof import('./src/components/cloud/CloudListItem.vue')['default']
    HaList: typeof import('./src/components/homeAssistant/HaList.vue')['default']
    HaListItem: typeof import('./src/components/homeAssistant/HaListItem.vue')['default']
    HaListItemContent: typeof import('./src/components/homeAssistant/HaListItemContent.vue')['default']
    MessageBar: typeof import('./src/components/MessageBar.vue')['default']
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WebdavConfigForm: typeof import('./src/components/settings/WebdavConfigForm.vue')['default']
    WebdavConfigMenu: typeof import('./src/components/settings/WebdavConfigMenu.vue')['default']
  }
}
